### ISSUE TITLE
[Improvement] Academic search interface does not support mouse wheel scrolling (touchscreen-only navigation)

### ISSUE THREAD

**Issue by MrPeterJin** [zaidmukaddam/scira#70]
**Description:**When using the academic search feature, the search results panel or content area cannot be scrolled with a mouse wheel, though it works as expected with touchscreen gestures (e.g., swiping on a touchpad or mobile device). This creates a poor user experience for desktop/laptop users relying on traditional mouse input.

**Steps to Reproduce:**
1. Perform a search on the academic search page.
2. Attempt to scroll through results using the mouse wheel.
3. Observe that the page/content does not scroll.
4. Use touch gestures (e.g., two-finger swipe on a touchpad) and confirm scrolling works.

**Expected Behavior:**
Both mouse wheel and touch gestures should enable smooth scrolling in the search results panel.

**Comment by zaidmukaddam** [comment]
Hey, this has been fixed now, will be closing this issue.

**Comment by MrPeterJin** [comment]
![Image](https://github.com/user-attachments/assets/d8b43cb2-7c8d-4351-b5b9-3507e6d743c6)

Hi!
When I am accessing scira.app and click random trend term for an academic search, it is still not scrollable. Is it something I missed?
